"""
questions.py – Question banks separated by grade level (1–6) and subject.

Door subjects:
    Door 1 → Grammar
    Door 2 → Vocabulary
    Door 3 → Science

Each grade has exactly 5 questions per subject (15 questions per grade).
A random question is drawn from the selected grade's pool when the player
first touches a door.

Entry format: {q, opts, ans, cat}
    q    – question prompt string
    opts – list of exactly 4 answer strings
    ans  – index of the correct answer (0 / 1 / 2 / 3)
    cat  – category label (used as badge on the question screen)
"""

# ─── Grammar question bank ────────────────────────────────────────────────────
GRAMMAR_QS = {
    1: [
        {"q": "Which sentence is correct?",
         "opts": ["She run fast.", "She runs fast.", "She running fast.", "She runned fast."],
         "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a verb?",
         "opts": ["apple", "big", "run", "happy"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Pick the correct sentence:",
         "opts": ["He have a dog.", "He having a dog.", "He has a dog.", "He haves a dog."],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which word is a noun?",
         "opts": ["jump", "quickly", "bright", "cat"],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which sentence uses 'am' correctly?",
         "opts": ["She am happy.", "I am happy.", "They am happy.", "He am happy."],
         "ans": 1, "cat": "Grammar"},
    ],
    2: [
        {"q": "What is the plural of 'child'?",
         "opts": ["Childs", "Childrens", "Childes", "Children"],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which uses the article 'an' correctly?",
         "opts": ["an book", "an cat", "an apple", "an dog"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is complete?",
         "opts": ["Ran very fast.", "The big dog.", "Under the tree.", "The dog ran home."],
         "ans": 3, "cat": "Grammar"},
        {"q": "What is the plural of 'tooth'?",
         "opts": ["Tooths", "Teethes", "Tooths", "Teeth"],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which sentence has the correct verb?",
         "opts": ["We is going.", "We are going.", "We am going.", "We be going."],
         "ans": 1, "cat": "Grammar"},
    ],
    3: [
        {"q": "Which is the correct past tense of 'go'?",
         "opts": ["He goed.", "He goes.", "He go.", "He went."],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which uses 'they're' correctly?",
         "opts": ["They're book is lost.", "They're going home.", "Their going home.", "There going home."],
         "ans": 1, "cat": "Grammar"},
        {"q": "What is the past tense of 'write'?",
         "opts": ["writed", "writ", "wrote", "wroten"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which contraction is correct?",
         "opts": ["ca'nt", "cant", "can't", "c'ant"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Identify the adjective: 'The tall boy runs fast.'",
         "opts": ["The", "runs", "fast", "tall"],
         "ans": 3, "cat": "Grammar"},
    ],
    4: [
        {"q": "Which is a proper noun?",
         "opts": ["city", "river", "mountain", "London"],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which word is an adverb?",
         "opts": ["beautiful", "beauty", "quickly", "quick"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which uses a comma correctly?",
         "opts": ["I like, cats and dogs.", "I like cats and, dogs.", "I like cats, and dogs.", "I like cats and dogs,"],
         "ans": 2, "cat": "Grammar"},
        {"q": "What is the correct past tense of 'sing'?",
         "opts": ["singed", "sung", "sanged", "sang"],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["quickly", "London", "and", "beautiful"],
         "ans": 2, "cat": "Grammar"},
    ],
    5: [
        {"q": "Identify the adverb: 'She sings beautifully.'",
         "opts": ["She", "sings", "beautifully", "the"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which is a compound sentence?",
         "opts": ["She runs.", "Running fast is fun.", "She runs and she jumps.", "Although she was tired."],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses the subjunctive mood?",
         "opts": ["She sings well.", "She sang a song.", "She will sing.", "If she were here, I'd be happy."],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which uses a colon correctly?",
         "opts": ["I need: to go.", "I need three things: milk, eggs, bread.", "I: need things.", "I need things:"],
         "ans": 1, "cat": "Grammar"},
        {"q": "What type of pronoun is 'himself'?",
         "opts": ["Personal", "Possessive", "Reflexive", "Relative"],
         "ans": 2, "cat": "Grammar"},
    ],
    6: [
        {"q": "Which is written in the passive voice?",
         "opts": ["The dog chased the cat.", "The cat ran away.", "The cat was chased by the dog.", "She quickly ran home."],
         "ans": 2, "cat": "Grammar"},
        {"q": "Which correctly uses a semicolon?",
         "opts": ["I run; fast.", "I; run fast.", "I run; I am fast.", "I run fast;"],
         "ans": 2, "cat": "Grammar"},
        {"q": "Identify the type of clause: 'because she was tired'",
         "opts": ["Independent clause", "Main clause", "Noun phrase", "Dependent clause"],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which is a complex sentence?",
         "opts": ["She runs.", "She runs and she jumps.", "She runs or she walks.", "Although she was tired, she finished."],
         "ans": 3, "cat": "Grammar"},
        {"q": "Which sentence contains a dangling modifier?",
         "opts": ["Running fast, she won the race.", "She won the race by running fast.", "Running fast, the trophy was won.", "She ran fast and won."],
         "ans": 2, "cat": "Grammar"},
    ],
}

# ─── Vocabulary question bank ─────────────────────────────────────────────────
VOCAB_QS = {
    1: [
        {"q": "Which word means 'very big'?",
         "opts": ["tiny", "fast", "huge", "cold"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "Which animal has wings AND feathers?",
         "opts": ["Fish", "Dog", "Bat", "Bird"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "What is the opposite of 'day'?",
         "opts": ["Morning", "Evening", "Night", "Noon"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What do we use to write on paper?",
         "opts": ["Spoon", "Shoe", "Pencil", "Pillow"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "Which word means 'to move very quickly'?",
         "opts": ["sleep", "run", "sit", "walk"],
         "ans": 1, "cat": "Vocabulary"},
    ],
    2: [
        {"q": "What is the opposite of 'hot'?",
         "opts": ["Warm", "Cool", "Cold", "Sunny"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "Which word rhymes with 'cake'?",
         "opts": ["Ball", "Cup", "Sock", "Lake"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "What is the opposite of 'start'?",
         "opts": ["Begin", "Continue", "Pause", "Finish"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "Which word means 'to look at something carefully'?",
         "opts": ["Touch", "Smell", "Listen", "Observe"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "What is the opposite of 'happy'?",
         "opts": ["Joyful", "Excited", "Sad", "Brave"],
         "ans": 2, "cat": "Vocabulary"},
    ],
    3: [
        {"q": "What does 'enormous' mean?",
         "opts": ["Very fast", "Very small", "Very cold", "Very large"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "Which word is a synonym for 'brave'?",
         "opts": ["Fearful", "Timid", "Courageous", "Tired"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What does 'ancient' mean?",
         "opts": ["Very new", "Very fast", "Very rare", "Very old"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "What does 'exhausted' mean?",
         "opts": ["Energetic", "Hungry", "Extremely tired", "Excited"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "Which word is a synonym for 'begin'?",
         "opts": ["End", "Stop", "Finish", "Commence"],
         "ans": 3, "cat": "Vocabulary"},
    ],
    4: [
        {"q": "What does 'cautious' mean?",
         "opts": ["Brave and bold", "Reckless", "Careful and alert", "Confused"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What is the antonym of 'generous'?",
         "opts": ["Kind", "Giving", "Selfish", "Charitable"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What does 'weary' mean?",
         "opts": ["Full of energy", "Deeply tired", "Very angry", "Extremely happy"],
         "ans": 1, "cat": "Vocabulary"},
        {"q": "Which word is a synonym for 'intelligent'?",
         "opts": ["Foolish", "Slow", "Bright", "Confused"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What does 'vivid' mean?",
         "opts": ["Dull and grey", "Very angry", "Bright and clear", "Old and faded"],
         "ans": 2, "cat": "Vocabulary"},
    ],
    5: [
        {"q": "What does 'benevolent' mean?",
         "opts": ["Cruel and cold", "Fearless and bold", "Angry and bitter", "Kind and generous"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "What does 'tenacious' mean?",
         "opts": ["Giving up easily", "Shy and quiet", "Persistent and determined", "Confused"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What does 'eloquent' mean?",
         "opts": ["Clumsy with words", "Angry in tone", "Silent and withdrawn", "Fluent and persuasive in speech"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "What does 'serene' mean?",
         "opts": ["Loud and chaotic", "Calm and peaceful", "Furious and wild", "Cold and harsh"],
         "ans": 1, "cat": "Vocabulary"},
        {"q": "What does 'melancholy' mean?",
         "opts": ["Full of excitement", "Very angry", "Deep sadness", "Total confusion"],
         "ans": 2, "cat": "Vocabulary"},
    ],
    6: [
        {"q": "What does 'ambiguous' mean?",
         "opts": ["Perfectly clear", "Open to more than one interpretation", "Completely false", "Very ancient"],
         "ans": 1, "cat": "Vocabulary"},
        {"q": "What does 'ephemeral' mean?",
         "opts": ["Lasting forever", "Extremely important", "Lasting only a very short time", "Impossible to see"],
         "ans": 2, "cat": "Vocabulary"},
        {"q": "What does 'loquacious' mean?",
         "opts": ["Very quiet", "Tends to talk a great deal", "Extremely logical", "Easily confused"],
         "ans": 1, "cat": "Vocabulary"},
        {"q": "What does 'ubiquitous' mean?",
         "opts": ["Extremely rare", "Very ancient", "Impossible to understand", "Appearing everywhere at once"],
         "ans": 3, "cat": "Vocabulary"},
        {"q": "An 'oxymoron' is:",
         "opts": ["A word with the same meaning", "A word that sounds like its meaning", "Two words that mean the opposite", "Contradictory terms used together"],
         "ans": 3, "cat": "Vocabulary"},
    ],
}

# ─── Science question bank ────────────────────────────────────────────────────
SCIENCE_QS = {
    1: [
        {"q": "What do plants need to grow?",
         "opts": ["Juice and music", "Just water", "Sunlight, water, and air", "Only soil"],
         "ans": 2, "cat": "Science"},
        {"q": "How many legs does a spider have?",
         "opts": ["4", "6", "10", "8"],
         "ans": 3, "cat": "Science"},
        {"q": "Which animal lives only in water?",
         "opts": ["Dog", "Cat", "Bird", "Fish"],
         "ans": 3, "cat": "Science"},
        {"q": "What falls from clouds during a storm?",
         "opts": ["Only snow", "Only hail", "Only sunshine", "Rain or snow"],
         "ans": 3, "cat": "Science"},
        {"q": "What do we breathe in to stay alive?",
         "opts": ["Carbon dioxide", "Steam", "Smoke", "Oxygen"],
         "ans": 3, "cat": "Science"},
    ],
    2: [
        {"q": "What do caterpillars eventually become?",
         "opts": ["Birds", "Fish", "Spiders", "Butterflies or moths"],
         "ans": 3, "cat": "Science"},
        {"q": "Which of these is a solid?",
         "opts": ["Water", "Steam", "Air", "Ice"],
         "ans": 3, "cat": "Science"},
        {"q": "Where do fish breathe through?",
         "opts": ["Lungs", "Skin", "Nose", "Gills"],
         "ans": 3, "cat": "Science"},
        {"q": "What do we call a young frog?",
         "opts": ["Cub", "Kitten", "Foal", "Tadpole"],
         "ans": 3, "cat": "Science"},
        {"q": "Which is NOT a state of matter?",
         "opts": ["Solid", "Liquid", "Gas", "Energy"],
         "ans": 3, "cat": "Science"},
    ],
    3: [
        {"q": "Which organ pumps blood around the body?",
         "opts": ["Lungs", "Brain", "Kidney", "Heart"],
         "ans": 3, "cat": "Science"},
        {"q": "What type of rock is formed from cooled lava?",
         "opts": ["Sedimentary", "Metamorphic", "Limestone", "Igneous"],
         "ans": 3, "cat": "Science"},
        {"q": "What is the largest planet in our solar system?",
         "opts": ["Earth", "Saturn", "Mars", "Jupiter"],
         "ans": 3, "cat": "Science"},
        {"q": "What is the center of an atom called?",
         "opts": ["Electron", "Proton", "Shell", "Nucleus"],
         "ans": 3, "cat": "Science"},
        {"q": "Which organ do we use to filter waste from blood?",
         "opts": ["Heart", "Liver", "Lungs", "Kidneys"],
         "ans": 3, "cat": "Science"},
    ],
    4: [
        {"q": "How many planets are in our solar system?",
         "opts": ["7", "9", "10", "8"],
         "ans": 3, "cat": "Science"},
        {"q": "What causes day and night on Earth?",
         "opts": ["Earth revolving around the sun", "The moon's orbit", "Clouds blocking the sun", "Earth rotating on its axis"],
         "ans": 3, "cat": "Science"},
        {"q": "What is the process by which plants make food?",
         "opts": ["Respiration", "Evaporation", "Digestion", "Photosynthesis"],
         "ans": 3, "cat": "Science"},
        {"q": "What layer of Earth sits directly below the crust?",
         "opts": ["Inner core", "Outer core", "Magma chamber", "Mantle"],
         "ans": 3, "cat": "Science"},
        {"q": "Which planet is known as the Red Planet?",
         "opts": ["Venus", "Jupiter", "Mercury", "Mars"],
         "ans": 3, "cat": "Science"},
    ],
    5: [
        {"q": "Which organelle is known as the powerhouse of the cell?",
         "opts": ["Nucleus", "Ribosome", "Cell membrane", "Mitochondria"],
         "ans": 3, "cat": "Science"},
        {"q": "What is the boiling point of water in Celsius?",
         "opts": ["80°C", "90°C", "110°C", "100°C"],
         "ans": 3, "cat": "Science"},
        {"q": "Which vitamin does sunlight help the body produce?",
         "opts": ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
         "ans": 3, "cat": "Science"},
        {"q": "What force pulls objects toward Earth?",
         "opts": ["Magnetism", "Friction", "Air resistance", "Gravity"],
         "ans": 3, "cat": "Science"},
        {"q": "What is the chemical symbol for gold?",
         "opts": ["Go", "Gd", "Ag", "Au"],
         "ans": 3, "cat": "Science"},
    ],
    6: [
        {"q": "What is the chemical formula for water?",
         "opts": ["CO2", "O2", "NaCl", "H2O"],
         "ans": 3, "cat": "Science"},
        {"q": "What does DNA stand for?",
         "opts": ["Digital Nucleic Acid", "Dynamic Nutrient Assembly", "Deoxyribose Nitrogen Acid", "Deoxyribonucleic Acid"],
         "ans": 3, "cat": "Science"},
        {"q": "Newton's first law of motion describes:",
         "opts": ["Gravity between masses", "Action and reaction", "Force equals mass times acceleration", "Inertia — objects resist changes in motion"],
         "ans": 3, "cat": "Science"},
        {"q": "Approximately how fast does light travel?",
         "opts": ["3,000 km/s", "30,000 km/s", "3,000,000 km/s", "300,000 km/s"],
         "ans": 3, "cat": "Science"},
        {"q": "Which gas makes up most of Earth's atmosphere?",
         "opts": ["Oxygen (O2)", "Carbon dioxide (CO2)", "Hydrogen (H2)", "Nitrogen (N2)"],
         "ans": 3, "cat": "Science"},
    ],
}

# ── Door → question pool lookup ───────────────────────────────────────────────
_SUBJECT_POOL = {
    1: GRAMMAR_QS,
    2: VOCAB_QS,
    3: SCIENCE_QS,
}


def get_door_question(door_num: int, grade: int) -> dict:
    """Return a random question for the given door number and grade."""
    import random
    pool     = _SUBJECT_POOL[door_num]
    grade_qs = pool.get(min(max(grade, 1), 6))
    return random.choice(grade_qs)


# ─── Bonus round questions ────────────────────────────────────────────────────
BONUS_POOL = [
    {"q": "Unscramble: E-L-P-P-A",           "opts": ["APPLE", "PAPER", "PANEL"],          "ans": 0},
    {"q": "Next in sequence: 2, 4, 6, 8, ?", "opts": ["9", "10", "12"],                    "ans": 1},
    {"q": "The sun ___ in the east.",         "opts": ["sets", "rises", "falls"],            "ans": 1},
    {"q": "7 x 7 + 1 = ?",                   "opts": ["48", "50", "56"],                    "ans": 1},
    {"q": "Antonym of 'brave':",              "opts": ["Bold", "Cowardly", "Strong"],        "ans": 1},
    {"q": "Fix: 'She don't know.'",           "opts": ["She doesn't know.", "She not know.", "She no know."], "ans": 0},
    {"q": "Largest planet in our solar system?", "opts": ["Earth", "Saturn", "Jupiter"],    "ans": 2},
    {"q": "Unscramble: R-D-I-F-E-N",          "opts": ["FINDER", "FRIEND", "FRIDGE"],       "ans": 1},
]

# ─── Per-level configuration ──────────────────────────────────────────────────
LEVEL_CFG = {
    1: {"locked": [],        "keys": []},
    2: {"locked": [],        "keys": []},
    3: {"locked": [],        "keys": []},
    4: {"locked": [1],       "keys": [(400, 320, 1)]},
    5: {"locked": [1, 3],    "keys": [(350, 290, 1), (760, 420, 3)]},
    6: {"locked": [1, 2, 3], "keys": [(300, 290, 1), (590, 430, 2), (770, 290, 3)]},
}
