"""
questions.py – Question banks separated by grade level (1–6) and subject.

Door subjects:
    Door 1 → Grammar
    Door 2 → Vocabulary
    Door 3 → Science

Each grade has exactly 30 questions per subject (90 questions per grade).
Questions are drawn from the grade-specific pool the player selected.

Entry format: {q, opts, ans, cat}
    q    – question prompt string
    opts – list of exactly 4 answer strings
    ans  – index of the correct answer (0 / 1 / 2 / 3)
    cat  – category label (used as badge on the question screen)
"""

# ─── Grammar question bank ────────────────────────────────────────────────────
GRAMMAR_QS = {
    1: [
        {"q": 'Which word is a noun in this sentence: "The dog barked loudly"?',
         "opts": ["barked", "loudly", "dog", "the"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is a verb?",
         "opts": ["teacher", "dance", "pencil", "table"], "ans": 1, "cat": "Grammar"},
        {"q": "Fill in the blank: She ___ my friend.",
         "opts": ["are", "am", "is", "be"], "ans": 2, "cat": "Grammar"},
        {"q": "Choose the correct sentence.",
         "opts": ["He walk to school.", "He walks to school.", "He walking to school.", "He walked school."], "ans": 1, "cat": "Grammar"},
        {"q": "What punctuation mark ends an excited sentence?",
         "opts": [".", "?", "!", ","], "ans": 2, "cat": "Grammar"},
        {"q": 'Which word is an adjective in this sentence: "The fluffy cat slept."?',
         "opts": ["fluffy", "slept", "cat", "the"], "ans": 0, "cat": "Grammar"},
        {"q": "Fill in the blank: They ___ playing soccer.",
         "opts": ["is", "are", "am", "be"], "ans": 1, "cat": "Grammar"},
        {"q": "Choose the correct pronoun.",
         "opts": ["Her went to the library.", "She went to the library.", "Him went to the library.", "Them went to the library."], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is correct?",
         "opts": ["my brother likes pizza", "My brother likes pizza.", "My Brother likes pizza.", "my Brother Likes pizza."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the plural of "baby"?',
         "opts": ["babys", "babies", "babyses", "babyes"], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word rhymes with "train"?',
         "opts": ["book", "rain", "car", "ship"], "ans": 1, "cat": "Grammar"},
        {"q": "Choose the correct sentence.",
         "opts": ["We was happy.", "We were happy.", "We is happy.", "We be happy."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the opposite of "ancient"?',
         "opts": ["old", "modern", "dusty", "huge"], "ans": 1, "cat": "Grammar"},
        {"q": 'Fill in the blank with a verb: "The rabbit ___ across the field."',
         "opts": ["soft", "hopped", "green", "quiet"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the past tense of "climb"?',
         "opts": ["climbs", "climbing", "climbed", "climbes"], "ans": 2, "cat": "Grammar"},
        {"q": "Choose the correct possessive word.",
         "opts": ["their backpack", "there backpack", "they're backpack", "them backpack"], "ans": 0, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["because", "purple", "quickly", "rabbit"], "ans": 0, "cat": "Grammar"},
        {"q": 'Fill in the blank: "Yesterday, I ___ a movie."',
         "opts": ["watch", "watched", "watches", "watching"], "ans": 1, "cat": "Grammar"},
        {"q": "What type of sentence gives a command?",
         "opts": ["Question", "Exclamation", "Imperative", "Statement"], "ans": 2, "cat": "Grammar"},
        {"q": 'Which sentence uses "but" correctly?',
         "opts": ["I was tired but I finished my homework.", "I was tired and homework.", "But I was homework.", "I tired but."], "ans": 0, "cat": "Grammar"},
        {"q": 'What is the contraction for "cannot"?',
         "opts": ["cant", "can't", "cannotn't", "canot"], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is an adverb in this sentence: "The turtle moved slowly."?',
         "opts": ["turtle", "moved", "slowly", "the"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses correct capitalization and punctuation?",
         "opts": ["where are you going", "Where are you going.", "Where are you going?", "where Are You Going?"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the future tense of "study"?',
         "opts": ["studied", "studying", "will study", "studies"], "ans": 2, "cat": "Grammar"},
        {"q": "Choose the correct homophone.",
         "opts": ["Please live your shoes by the door.", "Please leave your shoes by the door.", "Please leaf your shoes by the door.", "Please leev your shoes by the door."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the subject in this sentence: "The noisy students laughed loudly."?',
         "opts": ["laughed loudly", "noisy", "students", "loudly"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the predicate in this sentence: "The noisy students laughed loudly."?',
         "opts": ["The noisy students", "laughed loudly", "students", "noisy"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is written in past tense?",
         "opts": ["They play outside every day.", "They will play outside.", "They played outside yesterday.", "They are playing outside."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains both a conjunction and an adjective?",
         "opts": ["The dog barked.", "I ran quickly.", "The small cat slept and the dog barked.", "Jump high!"], "ans": 2, "cat": "Grammar"},
        {"q": "Which is a proper noun?",
         "opts": ["city", "teacher", "Sarah", "school"], "ans": 2, "cat": "Grammar"},
    ],
    2: [
        {"q": "Which word is a noun?",
         "opts": ["jump", "carrot", "quickly", "softly"], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a verb?",
         "opts": ["run", "happy", "yellow", "teacher"], "ans": 0, "cat": "Grammar"},
        {"q": "Fill in the blank: They ___ at school.",
         "opts": ["is", "are", "am", "be"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is correct?",
         "opts": ["She like cats.", "She likes cats.", "She liking cats.", "She cat likes."], "ans": 1, "cat": "Grammar"},
        {"q": "What punctuation mark ends a question?",
         "opts": [".", "!", "?", ","], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adjective?",
         "opts": ["slowly", "purple", "jump", "laugh"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the plural of "fox"?',
         "opts": ["foxs", "foxes", "foxies", "fox"], "ans": 1, "cat": "Grammar"},
        {"q": "Choose the correct pronoun.",
         "opts": ["Him is my friend.", "He is my friend.", "Her is my friend.", "Them is my friend."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the past tense of "walk"?',
         "opts": ["walks", "walking", "walked", "walker"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses capitalization correctly?",
         "opts": ["my Dog is cute.", "My dog is cute.", "my dog Is cute.", "My Dog Is Cute."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word rhymes with "light"?',
         "opts": ["night", "tree", "jump", "smile"], "ans": 0, "cat": "Grammar"},
        {"q": 'Fill in the blank: "Yesterday, we ___ soccer."',
         "opts": ["play", "played", "plays", "playing"], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["because", "rabbit", "shiny", "quietly"], "ans": 0, "cat": "Grammar"},
        {"q": "Which sentence is a command?",
         "opts": ["Where are you?", "Please clean your room.", "I like pizza.", "Wow, that is huge!"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the opposite of "difficult"?',
         "opts": ["hard", "easy", "giant", "quick"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the contraction for "I am"?',
         "opts": ["Im", "I'm", "Iam", "I'll"], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is an adverb?",
         "opts": ["turtle", "carefully", "blue", "pencil"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is written in future tense?",
         "opts": ["I eat breakfast.", "I ate breakfast.", "I will eat breakfast.", "I am breakfast."], "ans": 2, "cat": "Grammar"},
        {"q": "Choose the correct homophone.",
         "opts": ["Their going home.", "There going home.", "They're going home.", "Them going home."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a proper noun?",
         "opts": ["The girl ran.", "I visited Seoul.", "The cat slept.", "My teacher smiled."], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses commas correctly?",
         "opts": ["I bought apples oranges and bananas.", "I bought apples, oranges, and bananas.", "I bought apples oranges, and bananas.", "I bought, apples oranges and bananas."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the subject in this sentence: "The birds sang loudly."?',
         "opts": ["sang loudly", "loudly", "birds", "the"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the predicate in this sentence: "The birds sang loudly."?',
         "opts": ["The birds", "sang loudly", "loudly", "birds"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses quotation marks correctly?",
         "opts": ['Sarah said Hello.', '"Sarah said hello."', 'Sarah said, "Hello."', 'Sarah "said hello."'], "ans": 2, "cat": "Grammar"},
        {"q": 'Which word is a synonym for "angry"?',
         "opts": ["furious", "cheerful", "calm", "tiny"], "ans": 0, "cat": "Grammar"},
        {"q": "Which sentence contains both an adjective and an adverb?",
         "opts": ["The dog barked.", "The fluffy dog barked loudly.", "The dog ran.", "Bark loudly."], "ans": 1, "cat": "Grammar"},
        {"q": "What type of sentence expresses strong emotion?",
         "opts": ["Declarative", "Interrogative", "Exclamatory", "Imperative"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["yesterday i went to Busan.", "Yesterday I went to Busan.", "Yesterday i Went to busan.", "yesterday I went to busan."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is an antonym for "expand"?',
         "opts": ["stretch", "grow", "shrink", "increase"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses correct grammar?",
         "opts": ["Me and him went outside.", "Him and I went outside.", "He and I went outside.", "Her and me went outside."], "ans": 2, "cat": "Grammar"},
    ],
    3: [
        {"q": "Which word is a pronoun?",
         "opts": ["teacher", "quickly", "she", "bright"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Him likes soccer.", "He likes soccer.", "He like soccer.", "Him like soccer."], "ans": 1, "cat": "Grammar"},
        {"q": "What punctuation mark should be used at the end of a question?",
         "opts": [".", "!", "?", ";"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adjective?",
         "opts": ["loudly", "beautiful", "jump", "swim"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the plural of "leaf"?',
         "opts": ["leafs", "leaves", "leafes", "leavs"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses capitalization correctly?",
         "opts": ["my favorite city is Seoul.", "My favorite city is Seoul.", "My Favorite City is Seoul.", "my Favorite city is seoul."], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["because", "mountain", "quietly", "happy"], "ans": 0, "cat": "Grammar"},
        {"q": 'Fill in the blank: "The students ___ studying for the test."',
         "opts": ["is", "are", "am", "be"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the past tense of "catch"?',
         "opts": ["catched", "caught", "catching", "catches"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is an exclamation?",
         "opts": ["Where are you going?", "I enjoy reading.", "What an amazing performance!", "Please close the door."], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the contraction for "would not"?',
         "opts": ["wouldnt", "won't", "wouldn't", "would'nt"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adverb?",
         "opts": ["graceful", "silently", "dolphin", "notebook"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is written in future tense?",
         "opts": ["I cleaned my room.", "I clean my room.", "I will clean my room.", "I am cleaning my room."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses commas correctly?",
         "opts": ["We visited Tokyo Japan and Seoul.", "We visited Tokyo, Japan, and Seoul.", "We visited, Tokyo Japan and Seoul.", "We visited Tokyo Japan, and Seoul."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is a synonym for "rapid"?',
         "opts": ["slow", "quick", "ancient", "tiny"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the subject in this sentence: "The talented musician played beautifully."?',
         "opts": ["played beautifully", "talented", "musician", "beautifully"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the predicate in this sentence: "The talented musician played beautifully."?',
         "opts": ["The talented musician", "musician", "played beautifully", "beautifully"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses quotation marks correctly?",
         "opts": ['Ava said "I love science."', '"Ava said I love science."', 'Ava said, "I love science."', 'Ava "said I love science."'], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a proper noun?",
         "opts": ["My brother enjoys soccer.", "We visited the Han River.", "The puppy barked loudly.", "The flowers bloomed."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is an antonym for "increase"?',
         "opts": ["grow", "expand", "reduce", "improve"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses the correct homophone?",
         "opts": ["Their planning a trip.", "There planning a trip.", "They're planning a trip.", "Them planning a trip."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Last summer i traveled to Canada.", "Last summer I traveled to Canada.", "last summer I traveled to Canada.", "Last Summer I traveled to canada."], "ans": 1, "cat": "Grammar"},
        {"q": "What type of sentence asks a question?",
         "opts": ["Declarative", "Imperative", "Interrogative", "Exclamatory"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains both an adjective and an adverb?",
         "opts": ["The bird flew.", "The colorful bird flew gracefully.", "Fly quickly.", "The bird rested."], "ans": 1, "cat": "Grammar"},
        {"q": 'What does the prefix "re-" usually mean?',
         "opts": ["before", "again", "not", "full of"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses grammar correctly?",
         "opts": ["Me and Daniel finished the project.", "Daniel and me finished the project.", "Daniel and I finished the project.", "Him and Daniel finished the project."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a compound subject?",
         "opts": ["The cat slept.", "Emma and Liam studied together.", "The happy dog barked.", "The teacher smiled warmly."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the meaning of the suffix "-less"?',
         "opts": ["full of", "without", "before", "again"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses a semicolon correctly?",
         "opts": ["I enjoy reading; my sister prefers drawing.", "I enjoy; reading my sister prefers drawing.", "Reading is fun;.", "I; enjoy reading."], "ans": 0, "cat": "Grammar"},
        {"q": "Which sentence is written in passive voice?",
         "opts": ["The artist painted the mural.", "The mural was painted by the artist.", "The artist paints every day.", "The artist is painting the mural."], "ans": 1, "cat": "Grammar"},
    ],
    4: [
        {"q": "Which word is a pronoun?",
         "opts": ["teacher", "quickly", "she", "bright"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Him likes soccer.", "He likes soccer.", "He like soccer.", "Him like soccer."], "ans": 1, "cat": "Grammar"},
        {"q": "What punctuation mark should be used at the end of a question?",
         "opts": [".", "!", "?", ";"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adjective?",
         "opts": ["loudly", "beautiful", "jump", "swim"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the plural of "leaf"?',
         "opts": ["leafs", "leaves", "leafes", "leavs"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses capitalization correctly?",
         "opts": ["my favorite city is Seoul.", "My favorite city is Seoul.", "My Favorite City is Seoul.", "my Favorite city is seoul."], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["because", "mountain", "quietly", "happy"], "ans": 0, "cat": "Grammar"},
        {"q": 'Fill in the blank: "The students ___ studying for the test."',
         "opts": ["is", "are", "am", "be"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the past tense of "catch"?',
         "opts": ["catched", "caught", "catching", "catches"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is an exclamation?",
         "opts": ["Where are you going?", "I enjoy reading.", "What an amazing performance!", "Please close the door."], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the contraction for "would not"?',
         "opts": ["wouldnt", "won't", "wouldn't", "would'nt"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adverb?",
         "opts": ["graceful", "silently", "dolphin", "notebook"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is written in future tense?",
         "opts": ["I cleaned my room.", "I clean my room.", "I will clean my room.", "I am cleaning my room."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses commas correctly?",
         "opts": ["We visited Tokyo Japan and Seoul.", "We visited Tokyo, Japan, and Seoul.", "We visited, Tokyo Japan and Seoul.", "We visited Tokyo Japan, and Seoul."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is a synonym for "rapid"?',
         "opts": ["slow", "quick", "ancient", "tiny"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the subject in this sentence: "The talented musician played beautifully."?',
         "opts": ["played beautifully", "talented", "musician", "beautifully"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the predicate in this sentence: "The talented musician played beautifully."?',
         "opts": ["The talented musician", "musician", "played beautifully", "beautifully"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses quotation marks correctly?",
         "opts": ['Ava said "I love science."', '"Ava said I love science."', 'Ava said, "I love science."', 'Ava "said I love science."'], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a proper noun?",
         "opts": ["My brother enjoys soccer.", "We visited the Han River.", "The puppy barked loudly.", "The flowers bloomed."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is an antonym for "increase"?',
         "opts": ["grow", "expand", "reduce", "improve"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses the correct homophone?",
         "opts": ["Their planning a trip.", "There planning a trip.", "They're planning a trip.", "Them planning a trip."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Last summer i traveled to Canada.", "Last summer I traveled to Canada.", "last summer I traveled to Canada.", "Last Summer I traveled to canada."], "ans": 1, "cat": "Grammar"},
        {"q": "What type of sentence asks a question?",
         "opts": ["Declarative", "Imperative", "Interrogative", "Exclamatory"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains both an adjective and an adverb?",
         "opts": ["The bird flew.", "The colorful bird flew gracefully.", "Fly quickly.", "The bird rested."], "ans": 1, "cat": "Grammar"},
        {"q": 'What does the prefix "re-" usually mean?',
         "opts": ["before", "again", "not", "full of"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses grammar correctly?",
         "opts": ["Me and Daniel finished the project.", "Daniel and me finished the project.", "Daniel and I finished the project.", "Him and Daniel finished the project."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a compound subject?",
         "opts": ["The cat slept.", "Emma and Liam studied together.", "The happy dog barked.", "The teacher smiled warmly."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the meaning of the suffix "-less"?',
         "opts": ["full of", "without", "before", "again"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses a semicolon correctly?",
         "opts": ["I enjoy reading; my sister prefers drawing.", "I enjoy; reading my sister prefers drawing.", "Reading is fun;.", "I; enjoy reading."], "ans": 0, "cat": "Grammar"},
        {"q": "Which sentence is written in passive voice?",
         "opts": ["The artist painted the mural.", "The mural was painted by the artist.", "The artist paints every day.", "The artist is painting the mural."], "ans": 1, "cat": "Grammar"},
    ],
    5: [
        {"q": "Which word is a pronoun?",
         "opts": ["mountain", "quickly", "they", "bright"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Him enjoys basketball.", "He enjoys basketball.", "He enjoy basketball.", "Him enjoy basketball."], "ans": 1, "cat": "Grammar"},
        {"q": "Which punctuation mark ends an exclamatory sentence?",
         "opts": [".", "?", "!", ";"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adjective?",
         "opts": ["carefully", "enormous", "run", "quietly"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the plural form of "wolf"?',
         "opts": ["wolfs", "wolves", "wolfes", "wolvez"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses capitalization correctly?",
         "opts": ["my favorite book is Charlotte's Web.", "My favorite book is Charlotte's Web.", "My Favorite Book is Charlotte's Web.", "my Favorite book is charlotte's web."], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["although", "mountain", "softly", "cheerful"], "ans": 0, "cat": "Grammar"},
        {"q": 'Fill in the blank: "The players ___ practicing after school."',
         "opts": ["is", "are", "am", "be"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the past tense of "freeze"?',
         "opts": ["freezed", "froze", "freezing", "freezes"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is a question?",
         "opts": ["Please sit quietly.", "I enjoy science.", "Why are the lights off?", "What a beautiful painting!"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the contraction for "should not"?',
         "opts": ["shouldnt", "shouldn't", "should'nt", "shouldnot"], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is an adverb?",
         "opts": ["graceful", "rapidly", "dolphin", "notebook"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is written in future tense?",
         "opts": ["I completed my homework.", "I complete my homework.", "I will complete my homework.", "I am completing homework."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses commas correctly?",
         "opts": ["We visited Paris France London and Rome.", "We visited Paris, France, London, and Rome.", "We visited Paris France, London and Rome.", "We visited, Paris France London and Rome."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is a synonym for "enormous"?',
         "opts": ["tiny", "gigantic", "ancient", "rapid"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the subject in this sentence: "The experienced pilot landed safely."?',
         "opts": ["landed safely", "experienced", "pilot", "safely"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the predicate in this sentence: "The experienced pilot landed safely."?',
         "opts": ["The experienced pilot", "pilot", "landed safely", "safely"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses quotation marks correctly?",
         "opts": ['Noah said "The experiment worked."', '"Noah said the experiment worked."', 'Noah said, "The experiment worked."', 'Noah "said the experiment worked."'], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a proper noun?",
         "opts": ["My cousin moved to Australia.", "The puppy barked loudly.", "The flowers bloomed.", "The students studied."], "ans": 0, "cat": "Grammar"},
        {"q": 'Which word is an antonym for "expand"?',
         "opts": ["enlarge", "stretch", "shrink", "increase"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses the correct homophone?",
         "opts": ["Their planning the presentation.", "There planning the presentation.", "They're planning the presentation.", "Them planning the presentation."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Last winter i traveled to Japan.", "Last winter I traveled to Japan.", "last winter I traveled to Japan.", "Last Winter I traveled to japan."], "ans": 1, "cat": "Grammar"},
        {"q": "What type of sentence gives a command?",
         "opts": ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains both an adjective and an adverb?",
         "opts": ["The dog barked.", "The energetic athlete ran quickly.", "Run carefully.", "The athlete rested."], "ans": 1, "cat": "Grammar"},
        {"q": 'What does the prefix "pre-" usually mean?',
         "opts": ["after", "before", "not", "full of"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses grammar correctly?",
         "opts": ["Me and Olivia completed the assignment.", "Olivia and me completed the assignment.", "Olivia and I completed the assignment.", "Her and Olivia completed the assignment."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a compound predicate?",
         "opts": ["The bird sang.", "The actor smiled and waved.", "The teacher explained the lesson.", "The students listened quietly."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the meaning of the suffix "-ful"?',
         "opts": ["without", "before", "full of", "again"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses a semicolon correctly?",
         "opts": ["I enjoy science; my brother prefers history.", "I enjoy; science my brother prefers history.", "Science is interesting;.", "I; enjoy science."], "ans": 0, "cat": "Grammar"},
        {"q": "Which sentence is written in passive voice?",
         "opts": ["The mechanic repaired the car.", "The car was repaired by the mechanic.", "The mechanic repairs cars daily.", "The mechanic is repairing the car."], "ans": 1, "cat": "Grammar"},
    ],
    6: [
        {"q": "Which word is a pronoun?",
         "opts": ["mountain", "quickly", "they", "bright"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Him enjoys basketball.", "He enjoys basketball.", "He enjoy basketball.", "Him enjoy basketball."], "ans": 1, "cat": "Grammar"},
        {"q": "Which punctuation mark ends an exclamatory sentence?",
         "opts": [".", "?", "!", ";"], "ans": 2, "cat": "Grammar"},
        {"q": "Which word is an adjective?",
         "opts": ["carefully", "enormous", "run", "quietly"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the plural form of "wolf"?',
         "opts": ["wolfs", "wolves", "wolfes", "wolvez"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses capitalization correctly?",
         "opts": ["my favorite book is Charlotte's Web.", "My favorite book is Charlotte's Web.", "My Favorite Book is Charlotte's Web.", "my Favorite book is charlotte's web."], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is a conjunction?",
         "opts": ["although", "mountain", "softly", "cheerful"], "ans": 0, "cat": "Grammar"},
        {"q": 'Fill in the blank: "The players ___ practicing after school."',
         "opts": ["is", "are", "am", "be"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the past tense of "freeze"?',
         "opts": ["freezed", "froze", "freezing", "freezes"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is a question?",
         "opts": ["Please sit quietly.", "I enjoy science.", "Why are the lights off?", "What a beautiful painting!"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the contraction for "should not"?',
         "opts": ["shouldnt", "shouldn't", "should'nt", "shouldnot"], "ans": 1, "cat": "Grammar"},
        {"q": "Which word is an adverb?",
         "opts": ["graceful", "rapidly", "dolphin", "notebook"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence is written in future tense?",
         "opts": ["I completed my homework.", "I complete my homework.", "I will complete my homework.", "I am completing homework."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses commas correctly?",
         "opts": ["We visited Paris France London and Rome.", "We visited Paris, France, London, and Rome.", "We visited Paris France, London and Rome.", "We visited, Paris France London and Rome."], "ans": 1, "cat": "Grammar"},
        {"q": 'Which word is a synonym for "enormous"?',
         "opts": ["tiny", "gigantic", "ancient", "rapid"], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the subject in this sentence: "The experienced pilot landed safely."?',
         "opts": ["landed safely", "experienced", "pilot", "safely"], "ans": 2, "cat": "Grammar"},
        {"q": 'What is the predicate in this sentence: "The experienced pilot landed safely."?',
         "opts": ["The experienced pilot", "pilot", "landed safely", "safely"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses quotation marks correctly?",
         "opts": ['Noah said "The experiment worked."', '"Noah said the experiment worked."', 'Noah said, "The experiment worked."', 'Noah "said the experiment worked."'], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a proper noun?",
         "opts": ["My cousin moved to Australia.", "The puppy barked loudly.", "The flowers bloomed.", "The students studied."], "ans": 0, "cat": "Grammar"},
        {"q": 'Which word is an antonym for "expand"?',
         "opts": ["enlarge", "stretch", "shrink", "increase"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses the correct homophone?",
         "opts": ["Their planning the presentation.", "There planning the presentation.", "They're planning the presentation.", "Them planning the presentation."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence is written correctly?",
         "opts": ["Last winter i traveled to Japan.", "Last winter I traveled to Japan.", "last winter I traveled to Japan.", "Last Winter I traveled to japan."], "ans": 1, "cat": "Grammar"},
        {"q": "What type of sentence gives a command?",
         "opts": ["Declarative", "Interrogative", "Imperative", "Exclamatory"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains both an adjective and an adverb?",
         "opts": ["The dog barked.", "The energetic athlete ran quickly.", "Run carefully.", "The athlete rested."], "ans": 1, "cat": "Grammar"},
        {"q": 'What does the prefix "pre-" usually mean?',
         "opts": ["after", "before", "not", "full of"], "ans": 1, "cat": "Grammar"},
        {"q": "Which sentence uses grammar correctly?",
         "opts": ["Me and Olivia completed the assignment.", "Olivia and me completed the assignment.", "Olivia and I completed the assignment.", "Her and Olivia completed the assignment."], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence contains a compound predicate?",
         "opts": ["The bird sang.", "The actor smiled and waved.", "The teacher explained the lesson.", "The students listened quietly."], "ans": 1, "cat": "Grammar"},
        {"q": 'What is the meaning of the suffix "-ful"?',
         "opts": ["without", "before", "full of", "again"], "ans": 2, "cat": "Grammar"},
        {"q": "Which sentence uses a semicolon correctly?",
         "opts": ["I enjoy science; my brother prefers history.", "I enjoy; science my brother prefers history.", "Science is interesting;.", "I; enjoy science."], "ans": 0, "cat": "Grammar"},
        {"q": "Which sentence is written in passive voice?",
         "opts": ["The mechanic repaired the car.", "The car was repaired by the mechanic.", "The mechanic repairs cars daily.", "The mechanic is repairing the car."], "ans": 1, "cat": "Grammar"},
    ],
}

# ─── Vocabulary question bank ─────────────────────────────────────────────────
VOCAB_QS = {
    1: [
        {"q": 'What does "cheerful" mean?',
         "opts": ["Sad", "Happy", "Angry", "Sleepy"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is another word for "large"?',
         "opts": ["Tiny", "Huge", "Quiet", "Cold"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "ancient"?',
         "opts": ["Modern", "Old", "Broken", "Dusty"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "tiny" mean?',
         "opts": ["Very large", "Very small", "Very loud", "Very old"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "quick"?',
         "opts": ["Rapid", "Sleepy", "Quiet", "Slow"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "giggle" mean?',
         "opts": ["To cry loudly", "To laugh softly", "To sleep quickly", "To run away"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "clever"?',
         "opts": ["Smart", "Slow", "Loud", "Tiny"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "arrive"?',
         "opts": ["Enter", "Leave", "Smile", "Watch"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "brave" mean?',
         "opts": ["Easily scared", "Strong and fearless", "Sleepy", "Confused"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "very thirsty"?',
         "opts": ["Hungry", "Exhausted", "Parched", "Tiny"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "begin"?',
         "opts": ["Finish", "Start", "Stop", "Pause"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "massive" mean?',
         "opts": ["Very small", "Very large", "Very quiet", "Very weak"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to examine carefully"?',
         "opts": ["Ignore", "Inspect", "Forget", "Whisper"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "modern"?',
         "opts": ["Ancient", "Bright", "New", "Quick"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "murmur" mean?',
         "opts": ["To shout", "To whisper softly", "To jump high", "To laugh loudly"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "beautiful"?',
         "opts": ["Ugly", "Lovely", "Dirty", "Weak"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to discover an answer"?',
         "opts": ["Solve", "Break", "Forget", "Wonder"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "exhausted" mean?',
         "opts": ["Full of energy", "Very tired", "Very hungry", "Very excited"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "success"?',
         "opts": ["Happiness", "Failure", "Victory", "Luck"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "predict" mean?',
         "opts": ["To remember the past", "To guess what may happen", "To solve a puzzle", "To describe a color"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to cooperate"?',
         "opts": ["Compete", "Ignore", "Collaborate", "Separate"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "furious"?',
         "opts": ["Calm", "Angry", "Excited", "Sleepy"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "observe" mean in science?',
         "opts": ["To destroy", "To watch carefully", "To ignore", "To guess randomly"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "generous"?',
         "opts": ["Kind", "Selfish", "Friendly", "Cheerful"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "fragile" mean?',
         "opts": ["Strong and heavy", "Easy to break", "Very large", "Very noisy"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "extremely important"?',
         "opts": ["Minor", "Critical", "Tiny", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "confused"?',
         "opts": ["Puzzled", "Certain", "Calm", "Brave"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "investigate" mean?',
         "opts": ["To look into something carefully", "To ignore something", "To forget quickly", "To sleep deeply"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "expand"?',
         "opts": ["Stretch", "Grow", "Shrink", "Increase"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'Which sentence uses the word "curious" correctly?',
         "opts": ["The curious boy asked many questions.", "The curious rock flew away.", "The curious sandwich barked loudly.", "The curious pencil slept all day."], "ans": 0, "cat": "Vocabulary"},
    ],
    2: [
        {"q": 'What does "joyful" mean?',
         "opts": ["Sad", "Happy", "Angry", "Tired"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "tiny"?',
         "opts": ["Huge", "Small", "Loud", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "empty"?',
         "opts": ["Full", "Broken", "Tiny", "Quiet"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "swift" mean?',
         "opts": ["Slow", "Fast", "Sleepy", "Weak"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "very smart"?',
         "opts": ["Clever", "Angry", "Hungry", "Tiny"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "whisper" mean?',
         "opts": ["To shout loudly", "To speak softly", "To sing loudly", "To run quickly"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "ancient"?',
         "opts": ["Modern", "Dusty", "Old", "Broken"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "afraid"?',
         "opts": ["Brave", "Nervous", "Calm", "Cheerful"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "gigantic" mean?',
         "opts": ["Very small", "Very large", "Very quiet", "Very weak"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "begin"?',
         "opts": ["End", "Start", "Stop", "Finish"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "observe" mean?',
         "opts": ["To watch carefully", "To ignore", "To sleep", "To hide"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "extremely tired"?',
         "opts": ["Excited", "Exhausted", "Cheerful", "Curious"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "generous"?',
         "opts": ["Kind", "Selfish", "Helpful", "Friendly"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "easy to break"?',
         "opts": ["Strong", "Fragile", "Heavy", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "predict" mean?',
         "opts": ["To guess what may happen", "To erase something", "To watch TV", "To remember perfectly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "furious"?',
         "opts": ["Calm", "Angry", "Cheerful", "Sleepy"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to look for answers"?',
         "opts": ["Ignore", "Investigate", "Relax", "Wander"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "expand"?',
         "opts": ["Grow", "Stretch", "Shrink", "Increase"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'Which word means "very important"?',
         "opts": ["Tiny", "Critical", "Quiet", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "cooperate" mean?',
         "opts": ["To work together", "To argue loudly", "To sleep", "To hide"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "confused"?',
         "opts": ["Certain", "Puzzled", "Calm", "Brave"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "cautious" mean?',
         "opts": ["Careful", "Loud", "Fast", "Silly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to encourage someone"?',
         "opts": ["Discourage", "Motivate", "Ignore", "Hide"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "victory"?',
         "opts": ["Success", "Failure", "Happiness", "Strength"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to solve a problem"?',
         "opts": ["Forget", "Solve", "Break", "Wonder"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "efficient" mean?',
         "opts": ["Working well without wasting time", "Very loud", "Easily broken", "Extremely old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to adapt to new conditions"?',
         "opts": ["Refuse", "Adjust", "Collapse", "Ignore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "brilliant"?',
         "opts": ["Dull", "Intelligent", "Weak", "Silent"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word best describes someone who never gives up?',
         "opts": ["Lazy", "Determined", "Nervous", "Careless"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which sentence uses the word "curious" correctly?',
         "opts": ["The curious student asked many questions.", "The curious chair barked loudly.", "The curious sandwich ran away.", "The curious pencil ate lunch."], "ans": 0, "cat": "Vocabulary"},
    ],
    3: [
        {"q": 'What does "ancient" mean?',
         "opts": ["Very old", "Very fast", "Very loud", "Very small"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "happy"?',
         "opts": ["Cheerful", "Furious", "Tiny", "Weak"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "arrive"?',
         "opts": ["Enter", "Leave", "Observe", "Explore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "fragile" mean?',
         "opts": ["Easy to break", "Extremely strong", "Very loud", "Very old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "quick"?',
         "opts": ["Ancient", "Rapid", "Exhausted", "Silent"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "brilliant"?',
         "opts": ["Intelligent", "Weak", "Tiny", "Dull"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "cautious" mean?',
         "opts": ["Careful", "Loud", "Careless", "Sleepy"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to study carefully"?',
         "opts": ["Observe", "Ignore", "Wander", "Relax"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "expand"?',
         "opts": ["Stretch", "Increase", "Shrink", "Grow"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'What does "predict" mean?',
         "opts": ["To guess what may happen", "To erase information", "To hide something", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "extremely tired"?',
         "opts": ["Curious", "Exhausted", "Cheerful", "Furious"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "generous"?',
         "opts": ["Selfish", "Kind", "Lazy", "Nervous"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to work together"?',
         "opts": ["Compete", "Cooperate", "Ignore", "Wander"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "investigate" mean?',
         "opts": ["To look into something carefully", "To destroy something", "To sleep deeply", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "victory"?',
         "opts": ["Failure", "Celebration", "Success", "Strength"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "efficient" mean?',
         "opts": ["Working well without wasting time", "Easily broken", "Very loud", "Extremely old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "confused"?',
         "opts": ["Certain", "Puzzled", "Calm", "Brave"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "motivate" mean?',
         "opts": ["To discourage", "To inspire action", "To destroy", "To sleep"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "important"?',
         "opts": ["Minor", "Critical", "Tiny", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "scarce"?',
         "opts": ["Rare", "Abundant", "Weak", "Tiny"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "adapt" mean?',
         "opts": ["To stay the same forever", "To adjust to new conditions", "To disappear quickly", "To ignore problems"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "carefully planned"?',
         "opts": ["Organized", "Chaotic", "Random", "Ancient"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "fortunate"?',
         "opts": ["Lucky", "Angry", "Nervous", "Exhausted"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "consequence" mean?',
         "opts": ["A result of an action", "A cause", "A celebration", "A prediction"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word best describes someone who never gives up?',
         "opts": ["Determined", "Lazy", "Careless", "Silent"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "analyze" mean?',
         "opts": ["To examine something carefully", "To ignore information", "To destroy evidence", "To sleep deeply"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to improve something"?',
         "opts": ["Worsen", "Improve", "Collapse", "Ignore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "complex"?',
         "opts": ["Simple", "Complicated", "Tiny", "Loud"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "resourceful" mean?',
         "opts": ["Good at solving problems", "Easily frightened", "Extremely tired", "Very loud"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which sentence uses the word "curious" correctly?',
         "opts": ["The curious inventor tested many ideas.", "The curious sandwich barked loudly.", "The curious backpack danced.", "The curious pencil slept."], "ans": 0, "cat": "Vocabulary"},
    ],
    4: [
        {"q": 'What does "ancient" mean?',
         "opts": ["Very old", "Very fast", "Very loud", "Very small"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "happy"?',
         "opts": ["Cheerful", "Furious", "Tiny", "Weak"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "arrive"?',
         "opts": ["Enter", "Leave", "Observe", "Explore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "fragile" mean?',
         "opts": ["Easy to break", "Extremely strong", "Very loud", "Very old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "quick"?',
         "opts": ["Ancient", "Rapid", "Exhausted", "Silent"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "brilliant"?',
         "opts": ["Intelligent", "Weak", "Tiny", "Dull"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "cautious" mean?',
         "opts": ["Careful", "Loud", "Careless", "Sleepy"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to study carefully"?',
         "opts": ["Observe", "Ignore", "Wander", "Relax"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "expand"?',
         "opts": ["Stretch", "Increase", "Shrink", "Grow"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'What does "predict" mean?',
         "opts": ["To guess what may happen", "To erase information", "To hide something", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "extremely tired"?',
         "opts": ["Curious", "Exhausted", "Cheerful", "Furious"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "generous"?',
         "opts": ["Selfish", "Kind", "Lazy", "Nervous"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to work together"?',
         "opts": ["Compete", "Cooperate", "Ignore", "Wander"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "investigate" mean?',
         "opts": ["To look into something carefully", "To destroy something", "To sleep deeply", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "victory"?',
         "opts": ["Failure", "Celebration", "Success", "Strength"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "efficient" mean?',
         "opts": ["Working well without wasting time", "Easily broken", "Very loud", "Extremely old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "confused"?',
         "opts": ["Certain", "Puzzled", "Calm", "Brave"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "motivate" mean?',
         "opts": ["To discourage", "To inspire action", "To destroy", "To sleep"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "important"?',
         "opts": ["Minor", "Critical", "Tiny", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "scarce"?',
         "opts": ["Rare", "Abundant", "Weak", "Tiny"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "adapt" mean?',
         "opts": ["To stay the same forever", "To adjust to new conditions", "To disappear quickly", "To ignore problems"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "carefully planned"?',
         "opts": ["Organized", "Chaotic", "Random", "Ancient"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "fortunate"?',
         "opts": ["Lucky", "Angry", "Nervous", "Exhausted"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "consequence" mean?',
         "opts": ["A result of an action", "A cause", "A celebration", "A prediction"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word best describes someone who never gives up?',
         "opts": ["Determined", "Lazy", "Careless", "Silent"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "analyze" mean?',
         "opts": ["To examine something carefully", "To ignore information", "To destroy evidence", "To sleep deeply"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to improve something"?',
         "opts": ["Worsen", "Improve", "Collapse", "Ignore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "complex"?',
         "opts": ["Simple", "Complicated", "Tiny", "Loud"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "resourceful" mean?',
         "opts": ["Good at solving problems", "Easily frightened", "Extremely tired", "Very loud"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which sentence uses the word "curious" correctly?',
         "opts": ["The curious inventor tested many ideas.", "The curious sandwich barked loudly.", "The curious backpack danced.", "The curious pencil slept."], "ans": 0, "cat": "Vocabulary"},
    ],
    5: [
        {"q": 'What does "ancient" mean?',
         "opts": ["Very old", "Very loud", "Very fast", "Very small"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "happy"?',
         "opts": ["Cheerful", "Furious", "Weak", "Tiny"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "arrive"?',
         "opts": ["Enter", "Leave", "Observe", "Explore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "fragile" mean?',
         "opts": ["Easy to break", "Extremely strong", "Very loud", "Very old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "quick"?',
         "opts": ["Ancient", "Rapid", "Exhausted", "Silent"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "brilliant"?',
         "opts": ["Intelligent", "Weak", "Tiny", "Dull"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "cautious" mean?',
         "opts": ["Careful", "Careless", "Loud", "Sleepy"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to examine carefully"?',
         "opts": ["Observe", "Ignore", "Wander", "Relax"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "expand"?',
         "opts": ["Stretch", "Increase", "Shrink", "Grow"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'What does "predict" mean?',
         "opts": ["To guess what may happen", "To erase information", "To hide something", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "extremely tired"?',
         "opts": ["Curious", "Exhausted", "Cheerful", "Furious"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "generous"?',
         "opts": ["Selfish", "Kind", "Lazy", "Nervous"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to work together"?',
         "opts": ["Compete", "Cooperate", "Ignore", "Wander"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "investigate" mean?',
         "opts": ["To look into something carefully", "To destroy something", "To sleep deeply", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "victory"?',
         "opts": ["Failure", "Celebration", "Success", "Strength"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "efficient" mean?',
         "opts": ["Working well without wasting time", "Easily broken", "Very loud", "Extremely old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "confused"?',
         "opts": ["Certain", "Puzzled", "Calm", "Brave"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "motivate" mean?',
         "opts": ["To discourage", "To inspire action", "To destroy", "To sleep"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "important"?',
         "opts": ["Minor", "Critical", "Tiny", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "scarce"?',
         "opts": ["Rare", "Abundant", "Weak", "Tiny"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "adapt" mean?',
         "opts": ["To stay the same forever", "To adjust to new conditions", "To disappear quickly", "To ignore problems"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "carefully planned"?',
         "opts": ["Organized", "Chaotic", "Random", "Ancient"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "fortunate"?',
         "opts": ["Lucky", "Angry", "Nervous", "Exhausted"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "consequence" mean?',
         "opts": ["A result of an action", "A cause", "A celebration", "A prediction"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word best describes someone who never gives up?',
         "opts": ["Determined", "Lazy", "Careless", "Silent"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "analyze" mean?',
         "opts": ["To examine something carefully", "To ignore information", "To destroy evidence", "To sleep deeply"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to improve something"?',
         "opts": ["Worsen", "Improve", "Collapse", "Ignore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "complex"?',
         "opts": ["Simple", "Complicated", "Tiny", "Loud"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "resourceful" mean?',
         "opts": ["Good at solving problems", "Easily frightened", "Extremely tired", "Very loud"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which sentence uses the word "curious" correctly?',
         "opts": ["The curious engineer tested several solutions.", "The curious sandwich barked loudly.", "The curious backpack danced.", "The curious pencil slept."], "ans": 0, "cat": "Vocabulary"},
    ],
    6: [
        {"q": 'What does "ancient" mean?',
         "opts": ["Very old", "Very loud", "Very fast", "Very small"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "happy"?',
         "opts": ["Cheerful", "Furious", "Weak", "Tiny"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "arrive"?',
         "opts": ["Enter", "Leave", "Observe", "Explore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "fragile" mean?',
         "opts": ["Easy to break", "Extremely strong", "Very loud", "Very old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "quick"?',
         "opts": ["Ancient", "Rapid", "Exhausted", "Silent"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "brilliant"?',
         "opts": ["Intelligent", "Weak", "Tiny", "Dull"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "cautious" mean?',
         "opts": ["Careful", "Careless", "Loud", "Sleepy"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to examine carefully"?',
         "opts": ["Observe", "Ignore", "Wander", "Relax"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "expand"?',
         "opts": ["Stretch", "Increase", "Shrink", "Grow"], "ans": 2, "cat": "Vocabulary"},
        {"q": 'What does "predict" mean?',
         "opts": ["To guess what may happen", "To erase information", "To hide something", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "extremely tired"?',
         "opts": ["Curious", "Exhausted", "Cheerful", "Furious"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "generous"?',
         "opts": ["Selfish", "Kind", "Lazy", "Nervous"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "to work together"?',
         "opts": ["Compete", "Cooperate", "Ignore", "Wander"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "investigate" mean?',
         "opts": ["To look into something carefully", "To destroy something", "To sleep deeply", "To forget quickly"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "victory"?',
         "opts": ["Failure", "Celebration", "Success", "Strength"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "efficient" mean?',
         "opts": ["Working well without wasting time", "Easily broken", "Very loud", "Extremely old"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word is a synonym for "confused"?',
         "opts": ["Certain", "Puzzled", "Calm", "Brave"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "motivate" mean?',
         "opts": ["To discourage", "To inspire action", "To destroy", "To sleep"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "important"?',
         "opts": ["Minor", "Critical", "Tiny", "Ancient"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is the opposite of "scarce"?',
         "opts": ["Rare", "Abundant", "Weak", "Tiny"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "adapt" mean?',
         "opts": ["To stay the same forever", "To adjust to new conditions", "To disappear quickly", "To ignore problems"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'Which word means "carefully planned"?',
         "opts": ["Organized", "Chaotic", "Random", "Ancient"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "fortunate"?',
         "opts": ["Lucky", "Angry", "Nervous", "Exhausted"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "consequence" mean?',
         "opts": ["A result of an action", "A cause", "A celebration", "A prediction"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word best describes someone who never gives up?',
         "opts": ["Determined", "Lazy", "Careless", "Silent"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'What does "analyze" mean?',
         "opts": ["To examine something carefully", "To ignore information", "To destroy evidence", "To sleep deeply"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which word means "to improve something"?',
         "opts": ["Worsen", "Improve", "Collapse", "Ignore"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What is a synonym for "complex"?',
         "opts": ["Simple", "Complicated", "Tiny", "Loud"], "ans": 1, "cat": "Vocabulary"},
        {"q": 'What does "resourceful" mean?',
         "opts": ["Good at solving problems", "Easily frightened", "Extremely tired", "Very loud"], "ans": 0, "cat": "Vocabulary"},
        {"q": 'Which sentence uses the word "curious" correctly?',
         "opts": ["The curious engineer tested several solutions.", "The curious sandwich barked loudly.", "The curious backpack danced.", "The curious pencil slept."], "ans": 0, "cat": "Vocabulary"},
    ],
}

# ─── Science question bank ────────────────────────────────────────────────────
SCIENCE_QS = {
    1: [
        {"q": "How many legs does an insect have?",
         "opts": ["4", "6", "8", "10"], "ans": 1, "cat": "Science"},
        {"q": "What do plants need besides water to grow?",
         "opts": ["Candy", "Sunlight", "Toys", "Plastic"], "ans": 1, "cat": "Science"},
        {"q": "What is the moon?",
         "opts": ["Star", "Planet", "Satellite", "Comet"], "ans": 2, "cat": "Science"},
        {"q": "Which animal is known for building dams?",
         "opts": ["Lion", "Beaver", "Shark", "Eagle"], "ans": 1, "cat": "Science"},
        {"q": "What season comes before summer?",
         "opts": ["Winter", "Fall", "Spring", "Rainy"], "ans": 2, "cat": "Science"},
        {"q": "What gas do humans need to breathe?",
         "opts": ["Carbon dioxide", "Oxygen", "Helium", "Nitrogen"], "ans": 1, "cat": "Science"},
        {"q": "Which part of the plant carries water to the leaves?",
         "opts": ["Root", "Flower", "Stem", "Seed"], "ans": 2, "cat": "Science"},
        {"q": 'What planet is called the "Red Planet"?',
         "opts": ["Earth", "Mars", "Venus", "Saturn"], "ans": 1, "cat": "Science"},
        {"q": "Which mammal can fly?",
         "opts": ["Bat", "Penguin", "Whale", "Tiger"], "ans": 0, "cat": "Science"},
        {"q": "Why are bees important to flowers?",
         "opts": ["They pollinate them.", "They eat the roots.", "They freeze the flowers.", "They change the color."], "ans": 0, "cat": "Science"},
        {"q": "What force pulls objects toward Earth?",
         "opts": ["Magnetism", "Gravity", "Energy", "Friction"], "ans": 1, "cat": "Science"},
        {"q": "What do tadpoles grow into?",
         "opts": ["Fish", "Frogs", "Snakes", "Birds"], "ans": 1, "cat": "Science"},
        {"q": "Which body system helps you breathe?",
         "opts": ["Digestive system", "Respiratory system", "Nervous system", "Skeletal system"], "ans": 1, "cat": "Science"},
        {"q": "What gas do plants absorb from the air?",
         "opts": ["Oxygen", "Helium", "Carbon dioxide", "Hydrogen"], "ans": 2, "cat": "Science"},
        {"q": "Why is water important for living things?",
         "opts": ["It helps them survive.", "It changes colors.", "It makes rocks softer.", "It creates fire."], "ans": 0, "cat": "Science"},
        {"q": "What happens to water when it evaporates?",
         "opts": ["It freezes.", "It becomes a gas.", "It becomes solid.", "It disappears forever."], "ans": 1, "cat": "Science"},
        {"q": "What star is at the center of our solar system?",
         "opts": ["Moon", "Polaris", "Sun", "Mars"], "ans": 2, "cat": "Science"},
        {"q": "Which group correctly shows a solid, liquid, and gas?",
         "opts": ["Ice, water, steam", "Steam, rock, juice", "Juice, cloud, chair", "Air, milk, smoke"], "ans": 0, "cat": "Science"},
        {"q": "Why do plants appear green?",
         "opts": ["They absorb green light.", "They reflect green light.", "They create green paint.", "They glow naturally."], "ans": 1, "cat": "Science"},
        {"q": "What is the difference between herbivores and carnivores?",
         "opts": ["Herbivores eat plants.", "Carnivores eat plants.", "Herbivores fly.", "Carnivores make food."], "ans": 0, "cat": "Science"},
        {"q": "What causes the Earth to have day and night?",
         "opts": ["The moon moving", "The Earth spinning", "Clouds moving", "The sun spinning"], "ans": 1, "cat": "Science"},
        {"q": "Which stage comes after a caterpillar in a butterfly life cycle?",
         "opts": ["Egg", "Frog", "Chrysalis", "Seed"], "ans": 2, "cat": "Science"},
        {"q": "Why are some metals attracted to magnets?",
         "opts": ["They are warm.", "They contain magnetic materials.", "They are colorful.", "They are heavy."], "ans": 1, "cat": "Science"},
        {"q": "Which planet has the most visible rings?",
         "opts": ["Venus", "Mars", "Saturn", "Mercury"], "ans": 2, "cat": "Science"},
        {"q": "How are clouds formed?",
         "opts": ["Water vapor cools and condenses.", "Rocks melt in the sky.", "Smoke freezes.", "Trees create them."], "ans": 0, "cat": "Science"},
        {"q": "Why does the size of a shadow change during the day?",
         "opts": ["The Earth changes size.", "The sun's position changes.", "Shadows disappear randomly.", "Wind changes shadows."], "ans": 1, "cat": "Science"},
        {"q": "What is the difference between weather and climate?",
         "opts": ["Weather is short-term conditions.", "Climate changes every hour.", "Weather lasts for years.", "Climate means temperature only."], "ans": 0, "cat": "Science"},
        {"q": "Which are the three states of matter?",
         "opts": ["Hot, cold, warm", "Earth, wind, fire", "Solid, liquid, gas", "Hard, soft, smooth"], "ans": 2, "cat": "Science"},
        {"q": "Why is recycling important?",
         "opts": ["It wastes more energy.", "It helps reduce waste.", "It creates pollution.", "It destroys forests."], "ans": 1, "cat": "Science"},
        {"q": "What causes seasons on Earth?",
         "opts": ["The moon changing shape", "Earth's tilt and movement around the sun", "Clouds covering the sun", "Ocean waves"], "ans": 1, "cat": "Science"},
    ],
    2: [
        {"q": "Which animal is a mammal?",
         "opts": ["Shark", "Frog", "Dolphin", "Snake"], "ans": 2, "cat": "Science"},
        {"q": "What do plants use to make food?",
         "opts": ["Moonlight", "Sunlight", "Rocks", "Sand"], "ans": 1, "cat": "Science"},
        {"q": "What planet do humans live on?",
         "opts": ["Mars", "Venus", "Earth", "Jupiter"], "ans": 2, "cat": "Science"},
        {"q": "Which sense do you use with your ears?",
         "opts": ["Taste", "Sight", "Hearing", "Touch"], "ans": 2, "cat": "Science"},
        {"q": "Which season is usually the coldest?",
         "opts": ["Summer", "Spring", "Winter", "Fall"], "ans": 2, "cat": "Science"},
        {"q": "What do bees collect from flowers?",
         "opts": ["Honey", "Nectar", "Leaves", "Rocks"], "ans": 1, "cat": "Science"},
        {"q": "Which body part pumps blood?",
         "opts": ["Brain", "Lungs", "Heart", "Stomach"], "ans": 2, "cat": "Science"},
        {"q": "What do we call animals that only eat plants?",
         "opts": ["Carnivores", "Herbivores", "Omnivores", "Predators"], "ans": 1, "cat": "Science"},
        {"q": "What causes rain?",
         "opts": ["Frozen rocks", "Water falling from clouds", "Wind only", "Fire in the sky"], "ans": 1, "cat": "Science"},
        {"q": "Which object gives Earth light and heat?",
         "opts": ["Moon", "Sun", "Stars", "Clouds"], "ans": 1, "cat": "Science"},
        {"q": "What is the process called when water turns into vapor?",
         "opts": ["Freezing", "Melting", "Evaporation", "Condensation"], "ans": 2, "cat": "Science"},
        {"q": "Which organ helps humans think?",
         "opts": ["Heart", "Brain", "Lungs", "Bones"], "ans": 1, "cat": "Science"},
        {"q": "Why do plants need roots?",
         "opts": ["To fly", "To absorb water", "To make sounds", "To chase animals"], "ans": 1, "cat": "Science"},
        {"q": "Which planet is the largest in our solar system?",
         "opts": ["Earth", "Mars", "Jupiter", "Mercury"], "ans": 2, "cat": "Science"},
        {"q": "What are clouds mostly made of?",
         "opts": ["Dust", "Tiny water droplets", "Rocks", "Fire"], "ans": 1, "cat": "Science"},
        {"q": "Which state of matter keeps its own shape?",
         "opts": ["Liquid", "Gas", "Solid", "Steam"], "ans": 2, "cat": "Science"},
        {"q": "Why do magnets attract some metals?",
         "opts": ["They are cold.", "They contain iron.", "They are colorful.", "They are wet."], "ans": 1, "cat": "Science"},
        {"q": "What causes shadows?",
         "opts": ["Light being blocked", "Darkness moving", "Rain clouds", "Wind"], "ans": 0, "cat": "Science"},
        {"q": "Which animal goes through metamorphosis?",
         "opts": ["Butterfly", "Dog", "Cat", "Whale"], "ans": 0, "cat": "Science"},
        {"q": "What happens when ice melts?",
         "opts": ["It becomes gas.", "It becomes liquid water.", "It disappears.", "It turns into stone."], "ans": 1, "cat": "Science"},
        {"q": "What causes day and night?",
         "opts": ["Earth spinning on its axis", "Clouds moving", "The moon moving", "Rainstorms"], "ans": 0, "cat": "Science"},
        {"q": "Which planet is known for its rings?",
         "opts": ["Venus", "Saturn", "Earth", "Mars"], "ans": 1, "cat": "Science"},
        {"q": "Why is recycling helpful?",
         "opts": ["It increases trash.", "It protects the environment.", "It destroys forests.", "It wastes resources."], "ans": 1, "cat": "Science"},
        {"q": "Which body system includes the stomach and intestines?",
         "opts": ["Respiratory system", "Digestive system", "Skeletal system", "Nervous system"], "ans": 1, "cat": "Science"},
        {"q": "What is the main source of energy for Earth?",
         "opts": ["Wind", "Water", "The sun", "Rocks"], "ans": 2, "cat": "Science"},
        {"q": "Why do seasons change?",
         "opts": ["Earth tilts while moving around the sun.", "The moon changes shape.", "Clouds cover the sky.", "Wind changes direction."], "ans": 0, "cat": "Science"},
        {"q": "Which statement about matter is true?",
         "opts": ["Gases have no mass.", "Solids keep their shape.", "Liquids cannot move.", "Matter does not take up space."], "ans": 1, "cat": "Science"},
        {"q": "What happens during condensation?",
         "opts": ["Gas changes into liquid.", "Solid changes into liquid.", "Liquid changes into gas.", "Solid disappears."], "ans": 0, "cat": "Science"},
        {"q": "Which adaptation helps polar bears survive in cold places?",
         "opts": ["Thin fur", "Thick fur and fat", "Long tails", "Bright feathers"], "ans": 1, "cat": "Science"},
        {"q": "Why are producers important in a food chain?",
         "opts": ["They hunt animals.", "They make their own food.", "They destroy plants.", "They eat only meat."], "ans": 1, "cat": "Science"},
    ],
    3: [
        {"q": 'Which planet is known as the "Red Planet"?',
         "opts": ["Venus", "Mars", "Jupiter", "Mercury"], "ans": 1, "cat": "Science"},
        {"q": "What do plants need to make food?",
         "opts": ["Moonlight", "Sunlight", "Sand", "Plastic"], "ans": 1, "cat": "Science"},
        {"q": "Which organ helps humans breathe?",
         "opts": ["Brain", "Lungs", "Liver", "Bones"], "ans": 1, "cat": "Science"},
        {"q": "What state of matter is water vapor?",
         "opts": ["Solid", "Liquid", "Gas", "Plasma"], "ans": 2, "cat": "Science"},
        {"q": "Which animal is a mammal?",
         "opts": ["Snake", "Eagle", "Dolphin", "Frog"], "ans": 2, "cat": "Science"},
        {"q": "What force pulls objects toward Earth?",
         "opts": ["Friction", "Gravity", "Magnetism", "Electricity"], "ans": 1, "cat": "Science"},
        {"q": "What is the main source of energy for Earth?",
         "opts": ["Wind", "Water", "The sun", "Coal"], "ans": 2, "cat": "Science"},
        {"q": "Which layer of Earth do humans live on?",
         "opts": ["Mantle", "Core", "Crust", "Inner core"], "ans": 2, "cat": "Science"},
        {"q": "What process do plants use to make food?",
         "opts": ["Respiration", "Photosynthesis", "Digestion", "Evaporation"], "ans": 1, "cat": "Science"},
        {"q": "Which planet has the largest rings?",
         "opts": ["Earth", "Saturn", "Mars", "Venus"], "ans": 1, "cat": "Science"},
        {"q": "What is an ecosystem?",
         "opts": ["A type of cloud", "A community of living and nonliving things interacting", "A weather pattern", "A kind of animal"], "ans": 1, "cat": "Science"},
        {"q": "What causes earthquakes?",
         "opts": ["Windstorms", "Ocean waves", "Movement of tectonic plates", "Rainfall"], "ans": 2, "cat": "Science"},
        {"q": "What happens during evaporation?",
         "opts": ["Gas changes into liquid.", "Liquid changes into gas.", "Solid changes into liquid.", "Gas changes into solid."], "ans": 1, "cat": "Science"},
        {"q": "Which body system carries oxygen and nutrients through the body?",
         "opts": ["Digestive system", "Respiratory system", "Circulatory system", "Skeletal system"], "ans": 2, "cat": "Science"},
        {"q": "Which planet has the strongest gravity?",
         "opts": ["Earth", "Mars", "Jupiter", "Mercury"], "ans": 2, "cat": "Science"},
        {"q": "What is the function of chlorophyll in plants?",
         "opts": ["It absorbs sunlight for photosynthesis.", "It creates roots.", "It stores water.", "It makes flowers bloom."], "ans": 0, "cat": "Science"},
        {"q": "Why do magnets attract certain metals?",
         "opts": ["The metals are hot.", "The metals contain magnetic materials.", "The metals are colorful.", "The metals are light."], "ans": 1, "cat": "Science"},
        {"q": "What is a food web?",
         "opts": ["A single food chain", "A network of connected food chains", "A spider's home", "A weather map"], "ans": 1, "cat": "Science"},
        {"q": "Which adaptation helps penguins survive in cold climates?",
         "opts": ["Thin feathers", "Thick feathers and blubber", "Long tails", "Bright colors"], "ans": 1, "cat": "Science"},
        {"q": "What is condensation?",
         "opts": ["Gas turning into liquid", "Liquid turning into gas", "Solid turning into liquid", "Liquid turning into solid"], "ans": 0, "cat": "Science"},
        {"q": "Why do seasons change on Earth?",
         "opts": ["Earth tilts as it revolves around the sun.", "The moon changes shape.", "Clouds block sunlight.", "Wind changes direction."], "ans": 0, "cat": "Science"},
        {"q": "Which type of rock forms from heat and pressure?",
         "opts": ["Igneous", "Sedimentary", "Metamorphic", "Fossil"], "ans": 2, "cat": "Science"},
        {"q": "What is renewable energy?",
         "opts": ["Energy that cannot be replaced", "Energy from naturally replenished resources", "Energy made only from coal", "Energy stored underground forever"], "ans": 1, "cat": "Science"},
        {"q": "Which part of a cell controls its activities?",
         "opts": ["Cell membrane", "Cytoplasm", "Nucleus", "Vacuole"], "ans": 2, "cat": "Science"},
        {"q": "What role do decomposers play in ecosystems?",
         "opts": ["They produce sunlight.", "They break down dead organisms.", "They create weather.", "They stop plant growth."], "ans": 1, "cat": "Science"},
        {"q": "Why does the moon appear to change shape during the month?",
         "opts": ["The moon changes size.", "Different amounts of sunlight reflect off the moon.", "Clouds cover the moon.", "Earth changes shape."], "ans": 1, "cat": "Science"},
        {"q": "Which statement about atoms is true?",
         "opts": ["Atoms are larger than molecules.", "Atoms combine to form molecules.", "Atoms are living organisms.", "Atoms are made of clouds."], "ans": 1, "cat": "Science"},
        {"q": "What is the main function of the respiratory system?",
         "opts": ["To digest food", "To exchange oxygen and carbon dioxide", "To pump blood", "To support movement"], "ans": 1, "cat": "Science"},
        {"q": "Which example shows potential energy?",
         "opts": ["A rolling ball", "A stretched rubber band", "A moving bicycle", "Flowing water"], "ans": 1, "cat": "Science"},
        {"q": "Why are producers important in food chains?",
         "opts": ["They hunt animals.", "They make their own food and provide energy for others.", "They break down dead matter.", "They create weather."], "ans": 1, "cat": "Science"},
    ],
    4: [
        {"q": 'Which planet is known as the "Red Planet"?',
         "opts": ["Venus", "Mars", "Jupiter", "Mercury"], "ans": 1, "cat": "Science"},
        {"q": "What do plants need to make food?",
         "opts": ["Moonlight", "Sunlight", "Sand", "Plastic"], "ans": 1, "cat": "Science"},
        {"q": "Which organ helps humans breathe?",
         "opts": ["Brain", "Lungs", "Liver", "Bones"], "ans": 1, "cat": "Science"},
        {"q": "What state of matter is water vapor?",
         "opts": ["Solid", "Liquid", "Gas", "Plasma"], "ans": 2, "cat": "Science"},
        {"q": "Which animal is a mammal?",
         "opts": ["Snake", "Eagle", "Dolphin", "Frog"], "ans": 2, "cat": "Science"},
        {"q": "What force pulls objects toward Earth?",
         "opts": ["Friction", "Gravity", "Magnetism", "Electricity"], "ans": 1, "cat": "Science"},
        {"q": "What is the main source of energy for Earth?",
         "opts": ["Wind", "Water", "The sun", "Coal"], "ans": 2, "cat": "Science"},
        {"q": "Which layer of Earth do humans live on?",
         "opts": ["Mantle", "Core", "Crust", "Inner core"], "ans": 2, "cat": "Science"},
        {"q": "What process do plants use to make food?",
         "opts": ["Respiration", "Photosynthesis", "Digestion", "Evaporation"], "ans": 1, "cat": "Science"},
        {"q": "Which planet has the largest rings?",
         "opts": ["Earth", "Saturn", "Mars", "Venus"], "ans": 1, "cat": "Science"},
        {"q": "What is an ecosystem?",
         "opts": ["A type of cloud", "A community of living and nonliving things interacting", "A weather pattern", "A kind of animal"], "ans": 1, "cat": "Science"},
        {"q": "What causes earthquakes?",
         "opts": ["Windstorms", "Ocean waves", "Movement of tectonic plates", "Rainfall"], "ans": 2, "cat": "Science"},
        {"q": "What happens during evaporation?",
         "opts": ["Gas changes into liquid.", "Liquid changes into gas.", "Solid changes into liquid.", "Gas changes into solid."], "ans": 1, "cat": "Science"},
        {"q": "Which body system carries oxygen and nutrients through the body?",
         "opts": ["Digestive system", "Respiratory system", "Circulatory system", "Skeletal system"], "ans": 2, "cat": "Science"},
        {"q": "Which planet has the strongest gravity?",
         "opts": ["Earth", "Mars", "Jupiter", "Mercury"], "ans": 2, "cat": "Science"},
        {"q": "What is the function of chlorophyll in plants?",
         "opts": ["It absorbs sunlight for photosynthesis.", "It creates roots.", "It stores water.", "It makes flowers bloom."], "ans": 0, "cat": "Science"},
        {"q": "Why do magnets attract certain metals?",
         "opts": ["The metals are hot.", "The metals contain magnetic materials.", "The metals are colorful.", "The metals are light."], "ans": 1, "cat": "Science"},
        {"q": "What is a food web?",
         "opts": ["A single food chain", "A network of connected food chains", "A spider's home", "A weather map"], "ans": 1, "cat": "Science"},
        {"q": "Which adaptation helps penguins survive in cold climates?",
         "opts": ["Thin feathers", "Thick feathers and blubber", "Long tails", "Bright colors"], "ans": 1, "cat": "Science"},
        {"q": "What is condensation?",
         "opts": ["Gas turning into liquid", "Liquid turning into gas", "Solid turning into liquid", "Liquid turning into solid"], "ans": 0, "cat": "Science"},
        {"q": "Why do seasons change on Earth?",
         "opts": ["Earth tilts as it revolves around the sun.", "The moon changes shape.", "Clouds block sunlight.", "Wind changes direction."], "ans": 0, "cat": "Science"},
        {"q": "Which type of rock forms from heat and pressure?",
         "opts": ["Igneous", "Sedimentary", "Metamorphic", "Fossil"], "ans": 2, "cat": "Science"},
        {"q": "What is renewable energy?",
         "opts": ["Energy that cannot be replaced", "Energy from naturally replenished resources", "Energy made only from coal", "Energy stored underground forever"], "ans": 1, "cat": "Science"},
        {"q": "Which part of a cell controls its activities?",
         "opts": ["Cell membrane", "Cytoplasm", "Nucleus", "Vacuole"], "ans": 2, "cat": "Science"},
        {"q": "What role do decomposers play in ecosystems?",
         "opts": ["They produce sunlight.", "They break down dead organisms.", "They create weather.", "They stop plant growth."], "ans": 1, "cat": "Science"},
        {"q": "Why does the moon appear to change shape during the month?",
         "opts": ["The moon changes size.", "Different amounts of sunlight reflect off the moon.", "Clouds cover the moon.", "Earth changes shape."], "ans": 1, "cat": "Science"},
        {"q": "Which statement about atoms is true?",
         "opts": ["Atoms are larger than molecules.", "Atoms combine to form molecules.", "Atoms are living organisms.", "Atoms are made of clouds."], "ans": 1, "cat": "Science"},
        {"q": "What is the main function of the respiratory system?",
         "opts": ["To digest food", "To exchange oxygen and carbon dioxide", "To pump blood", "To support movement"], "ans": 1, "cat": "Science"},
        {"q": "Which example shows potential energy?",
         "opts": ["A rolling ball", "A stretched rubber band", "A moving bicycle", "Flowing water"], "ans": 1, "cat": "Science"},
        {"q": "Why are producers important in food chains?",
         "opts": ["They hunt animals.", "They make their own food and provide energy for others.", "They break down dead matter.", "They create weather."], "ans": 1, "cat": "Science"},
    ],
    5: [
        {"q": "Which planet is closest to the sun?",
         "opts": ["Venus", "Mercury", "Earth", "Mars"], "ans": 1, "cat": "Science"},
        {"q": "What do plants need for photosynthesis?",
         "opts": ["Sunlight", "Plastic", "Sand", "Smoke"], "ans": 0, "cat": "Science"},
        {"q": "Which organ pumps blood through the body?",
         "opts": ["Brain", "Lungs", "Heart", "Liver"], "ans": 2, "cat": "Science"},
        {"q": "What state of matter has a definite shape?",
         "opts": ["Liquid", "Gas", "Solid", "Vapor"], "ans": 2, "cat": "Science"},
        {"q": "Which animal is a vertebrate?",
         "opts": ["Earthworm", "Jellyfish", "Frog", "Octopus"], "ans": 2, "cat": "Science"},
        {"q": "What force keeps planets orbiting the sun?",
         "opts": ["Friction", "Gravity", "Magnetism", "Electricity"], "ans": 1, "cat": "Science"},
        {"q": "Which layer of Earth is made of molten rock?",
         "opts": ["Crust", "Mantle", "Atmosphere", "Ocean"], "ans": 1, "cat": "Science"},
        {"q": "What process changes liquid water into vapor?",
         "opts": ["Condensation", "Freezing", "Evaporation", "Melting"], "ans": 2, "cat": "Science"},
        {"q": "Which body system controls movement?",
         "opts": ["Respiratory system", "Digestive system", "Muscular system", "Circulatory system"], "ans": 2, "cat": "Science"},
        {"q": "Why do plants appear green?",
         "opts": ["They absorb green light.", "They reflect green light.", "They create green dye.", "They glow naturally."], "ans": 1, "cat": "Science"},
        {"q": "What is an ecosystem?",
         "opts": ["A weather event", "A community of organisms interacting with their environment", "A type of animal", "A layer of Earth"], "ans": 1, "cat": "Science"},
        {"q": "What causes tides in Earth's oceans?",
         "opts": ["Wind", "Earthquakes", "The gravitational pull of the moon", "Volcanoes"], "ans": 2, "cat": "Science"},
        {"q": "What is the function of the respiratory system?",
         "opts": ["To digest food", "To exchange oxygen and carbon dioxide", "To pump blood", "To support movement"], "ans": 1, "cat": "Science"},
        {"q": "Which type of rock forms from cooled magma or lava?",
         "opts": ["Sedimentary", "Metamorphic", "Igneous", "Fossil"], "ans": 2, "cat": "Science"},
        {"q": "What is the role of producers in a food chain?",
         "opts": ["They hunt animals.", "They make their own food.", "They break down dead organisms.", "They create weather."], "ans": 1, "cat": "Science"},
        {"q": "What is the function of chloroplasts in plant cells?",
         "opts": ["To store water", "To absorb sunlight for photosynthesis", "To create roots", "To protect the nucleus"], "ans": 1, "cat": "Science"},
        {"q": "What happens during condensation?",
         "opts": ["Liquid changes into gas.", "Gas changes into liquid.", "Solid changes into liquid.", "Gas changes into solid."], "ans": 1, "cat": "Science"},
        {"q": "Which adaptation helps polar bears survive in the Arctic?",
         "opts": ["Thin fur", "Thick fur and blubber", "Bright feathers", "Long tails"], "ans": 1, "cat": "Science"},
        {"q": "What is the purpose of the skeletal system?",
         "opts": ["To digest food", "To transport oxygen", "To support and protect the body", "To create energy"], "ans": 2, "cat": "Science"},
        {"q": "Why are decomposers important in ecosystems?",
         "opts": ["They produce sunlight.", "They recycle nutrients by breaking down dead organisms.", "They stop plant growth.", "They create weather."], "ans": 1, "cat": "Science"},
        {"q": "Why do seasons occur on Earth?",
         "opts": ["Earth changes distance from the sun.", "Earth tilts as it revolves around the sun.", "The moon changes shape.", "Wind patterns change."], "ans": 1, "cat": "Science"},
        {"q": "Which statement about atoms is true?",
         "opts": ["Atoms are larger than molecules.", "Atoms combine to form molecules.", "Atoms are living things.", "Atoms are made of clouds."], "ans": 1, "cat": "Science"},
        {"q": "What is renewable energy?",
         "opts": ["Energy that cannot be replaced", "Energy from resources that naturally replenish", "Energy stored underground forever", "Energy made only from coal"], "ans": 1, "cat": "Science"},
        {"q": "What causes earthquakes?",
         "opts": ["Windstorms", "Movement of tectonic plates", "Heavy rainfall", "Ocean currents"], "ans": 1, "cat": "Science"},
        {"q": "What is the function of the nucleus in a cell?",
         "opts": ["To create energy", "To control the cell's activities", "To protect the cell membrane", "To digest food"], "ans": 1, "cat": "Science"},
        {"q": "What is potential energy?",
         "opts": ["Energy of motion", "Stored energy", "Energy from heat", "Electrical energy"], "ans": 1, "cat": "Science"},
        {"q": "Why does the moon appear to change shape during the month?",
         "opts": ["The moon changes size.", "Different amounts of sunlight reflect off the moon.", "Clouds cover the moon.", "Earth changes shape."], "ans": 1, "cat": "Science"},
        {"q": "Which process moves water through plants?",
         "opts": ["Respiration", "Transpiration", "Condensation", "Digestion"], "ans": 1, "cat": "Science"},
        {"q": "Which statement about matter is correct?",
         "opts": ["Matter does not take up space.", "Gases have no mass.", "Matter has mass and takes up space.", "Solids cannot change shape."], "ans": 2, "cat": "Science"},
        {"q": "What is the primary purpose of the circulatory system?",
         "opts": ["To digest food", "To transport oxygen and nutrients through the body", "To help humans think", "To support movement"], "ans": 1, "cat": "Science"},
    ],
    6: [
        {"q": "Which planet is closest to the sun?",
         "opts": ["Venus", "Mercury", "Earth", "Mars"], "ans": 1, "cat": "Science"},
        {"q": "What do plants need for photosynthesis?",
         "opts": ["Sunlight", "Plastic", "Sand", "Smoke"], "ans": 0, "cat": "Science"},
        {"q": "Which organ pumps blood through the body?",
         "opts": ["Brain", "Lungs", "Heart", "Liver"], "ans": 2, "cat": "Science"},
        {"q": "What state of matter has a definite shape?",
         "opts": ["Liquid", "Gas", "Solid", "Vapor"], "ans": 2, "cat": "Science"},
        {"q": "Which animal is a vertebrate?",
         "opts": ["Earthworm", "Jellyfish", "Frog", "Octopus"], "ans": 2, "cat": "Science"},
        {"q": "What force keeps planets orbiting the sun?",
         "opts": ["Friction", "Gravity", "Magnetism", "Electricity"], "ans": 1, "cat": "Science"},
        {"q": "Which layer of Earth is made of molten rock?",
         "opts": ["Crust", "Mantle", "Atmosphere", "Ocean"], "ans": 1, "cat": "Science"},
        {"q": "What process changes liquid water into vapor?",
         "opts": ["Condensation", "Freezing", "Evaporation", "Melting"], "ans": 2, "cat": "Science"},
        {"q": "Which body system controls movement?",
         "opts": ["Respiratory system", "Digestive system", "Muscular system", "Circulatory system"], "ans": 2, "cat": "Science"},
        {"q": "Why do plants appear green?",
         "opts": ["They absorb green light.", "They reflect green light.", "They create green dye.", "They glow naturally."], "ans": 1, "cat": "Science"},
        {"q": "What is an ecosystem?",
         "opts": ["A weather event", "A community of organisms interacting with their environment", "A type of animal", "A layer of Earth"], "ans": 1, "cat": "Science"},
        {"q": "What causes tides in Earth's oceans?",
         "opts": ["Wind", "Earthquakes", "The gravitational pull of the moon", "Volcanoes"], "ans": 2, "cat": "Science"},
        {"q": "What is the function of the respiratory system?",
         "opts": ["To digest food", "To exchange oxygen and carbon dioxide", "To pump blood", "To support movement"], "ans": 1, "cat": "Science"},
        {"q": "Which type of rock forms from cooled magma or lava?",
         "opts": ["Sedimentary", "Metamorphic", "Igneous", "Fossil"], "ans": 2, "cat": "Science"},
        {"q": "What is the role of producers in a food chain?",
         "opts": ["They hunt animals.", "They make their own food.", "They break down dead organisms.", "They create weather."], "ans": 1, "cat": "Science"},
        {"q": "What is the function of chloroplasts in plant cells?",
         "opts": ["To store water", "To absorb sunlight for photosynthesis", "To create roots", "To protect the nucleus"], "ans": 1, "cat": "Science"},
        {"q": "What happens during condensation?",
         "opts": ["Liquid changes into gas.", "Gas changes into liquid.", "Solid changes into liquid.", "Gas changes into solid."], "ans": 1, "cat": "Science"},
        {"q": "Which adaptation helps polar bears survive in the Arctic?",
         "opts": ["Thin fur", "Thick fur and blubber", "Bright feathers", "Long tails"], "ans": 1, "cat": "Science"},
        {"q": "What is the purpose of the skeletal system?",
         "opts": ["To digest food", "To transport oxygen", "To support and protect the body", "To create energy"], "ans": 2, "cat": "Science"},
        {"q": "Why are decomposers important in ecosystems?",
         "opts": ["They produce sunlight.", "They recycle nutrients by breaking down dead organisms.", "They stop plant growth.", "They create weather."], "ans": 1, "cat": "Science"},
        {"q": "Why do seasons occur on Earth?",
         "opts": ["Earth changes distance from the sun.", "Earth tilts as it revolves around the sun.", "The moon changes shape.", "Wind patterns change."], "ans": 1, "cat": "Science"},
        {"q": "Which statement about atoms is true?",
         "opts": ["Atoms are larger than molecules.", "Atoms combine to form molecules.", "Atoms are living things.", "Atoms are made of clouds."], "ans": 1, "cat": "Science"},
        {"q": "What is renewable energy?",
         "opts": ["Energy that cannot be replaced", "Energy from resources that naturally replenish", "Energy stored underground forever", "Energy made only from coal"], "ans": 1, "cat": "Science"},
        {"q": "What causes earthquakes?",
         "opts": ["Windstorms", "Movement of tectonic plates", "Heavy rainfall", "Ocean currents"], "ans": 1, "cat": "Science"},
        {"q": "What is the function of the nucleus in a cell?",
         "opts": ["To create energy", "To control the cell's activities", "To protect the cell membrane", "To digest food"], "ans": 1, "cat": "Science"},
        {"q": "What is potential energy?",
         "opts": ["Energy of motion", "Stored energy", "Energy from heat", "Electrical energy"], "ans": 1, "cat": "Science"},
        {"q": "Why does the moon appear to change shape during the month?",
         "opts": ["The moon changes size.", "Different amounts of sunlight reflect off the moon.", "Clouds cover the moon.", "Earth changes shape."], "ans": 1, "cat": "Science"},
        {"q": "Which process moves water through plants?",
         "opts": ["Respiration", "Transpiration", "Condensation", "Digestion"], "ans": 1, "cat": "Science"},
        {"q": "Which statement about matter is correct?",
         "opts": ["Matter does not take up space.", "Gases have no mass.", "Matter has mass and takes up space.", "Solids cannot change shape."], "ans": 2, "cat": "Science"},
        {"q": "What is the primary purpose of the circulatory system?",
         "opts": ["To digest food", "To transport oxygen and nutrients through the body", "To help humans think", "To support movement"], "ans": 1, "cat": "Science"},
    ],
}

# ── Door → question pool lookup ───────────────────────────────────────────────
_SUBJECT_POOL = {
    1: GRAMMAR_QS,
    2: VOCAB_QS,
    3: SCIENCE_QS,
}


def get_door_question(door_num: int, grade: int) -> dict:
    """Return a random question for the given door number and grade."""
    import random
    pool     = _SUBJECT_POOL[door_num]
    grade_qs = pool.get(min(max(grade, 1), 6))
    return random.choice(grade_qs)


# ─── Bonus round questions ────────────────────────────────────────────────────
BONUS_POOL = [
    {"q": "Unscramble: E-L-P-P-A",           "opts": ["APPLE", "PAPER", "PANEL"],          "ans": 0},
    {"q": "Next in sequence: 2, 4, 6, 8, ?", "opts": ["9", "10", "12"],                    "ans": 1},
    {"q": "The sun ___ in the east.",         "opts": ["sets", "rises", "falls"],            "ans": 1},
    {"q": "7 x 7 + 1 = ?",                   "opts": ["48", "50", "56"],                    "ans": 1},
    {"q": "Antonym of 'brave':",              "opts": ["Bold", "Cowardly", "Strong"],        "ans": 1},
    {"q": "Fix: 'She don't know.'",           "opts": ["She doesn't know.", "She not know.", "She no know."], "ans": 0},
    {"q": "Largest planet in our solar system?", "opts": ["Earth", "Saturn", "Jupiter"],    "ans": 2},
    {"q": "Unscramble: R-D-I-F-E-N",          "opts": ["FINDER", "FRIEND", "FRIDGE"],       "ans": 1},
]

# ─── Per-level configuration ──────────────────────────────────────────────────
LEVEL_CFG = {
    1: {"locked": [],        "keys": []},
    2: {"locked": [],        "keys": []},
    3: {"locked": [],        "keys": []},
    4: {"locked": [1],       "keys": [(400, 320, 1)]},
    5: {"locked": [1, 3],    "keys": [(350, 290, 1), (760, 420, 3)]},
    6: {"locked": [1, 2, 3], "keys": [(300, 290, 1), (590, 430, 2), (770, 290, 3)]},
}
